// ============================================================
// @scout-agent/extension/extensions — 公开 API
// ============================================================

export { createEventBus, type EventBus, type EventBusController } from './event-bus.ts';
export type {
  ScoutToolDefinition,
  ScoutExtensionEventType,
  ResourcesDiscoverEvent,
  ResourcesDiscoverResult,
  BeforeAgentStartEvent,
  ContextEvent,
  ToolCallEvent,
  ToolResultEvent,
  BeforeProviderRequestEvent,
  AfterProviderResponseEvent,
  SessionBeforeCompactEvent,
  SessionCompactEvent,
  SessionShutdownEvent,
  ScoutExtensionEvent,
  BeforeAgentStartEventResult,
  ContextEventResult,
  ToolCallEventResult,
  ToolResultEventResult,
  BeforeProviderRequestEventResult,
  MessageEndEventResult,
  UserBashEventResult,
  InputEventResult,
  SessionBeforeCompactResult,
  SessionBeforeTreeEvent,
  SessionBeforeTreeResult,
  SessionTreeEvent,
  SessionBeforeForkEvent,
  SessionBeforeForkResult,
  SessionBeforeSwitchEvent,
  SessionBeforeSwitchResult,
  SessionStartEvent,
  AgentStartEvent,
  AgentEndEvent,
  TurnStartEvent,
  TurnEndEvent,
  MessageStartEvent,
  MessageUpdateEvent,
  MessageEndEvent,
  ToolExecutionStartEvent,
  ToolExecutionUpdateEvent,
  ToolExecutionEndEvent,
  ModelSelectEvent,
  ThinkingLevelSelectEvent,
  UserBashEvent,
  InputEvent,
  InputSource,
  ModelSelectSource,
  ScoutExtensionContext,
  ReplacedSessionContext,
  SessionReplacementOptions,
  SendMessagePayload,
  SendMessageInput,
  ScoutExtensionRuntime,
  ScoutExtension,
  RegisteredTool,
  ScoutExtensionError,
  ScoutHandlerFn,
  ScoutExtensionAPI,
  ScoutExtensionFactory,
  LoadExtensionsResult,
  ScoutExtensionActions,
  ScoutExtensionContextActions,
} from './types.ts';
export { wrapRegisteredTool, wrapRegisteredTools } from './wrapper.ts';
export {
  createExtensionRuntime,
  loadExtensionFromFactory,
  loadExtensions,
  discoverAndLoadExtensions,
} from './loader.ts';
export { ScoutExtensionRunner, type ScoutExtensionErrorListener } from './runner.ts';
