// ============================================================
// 内置模型目录 — 从 Pi 模型目录筛选并保留 Scout 支持的 provider
// Anthropic 来自 Pi generated catalog；OpenAI 当前保留 Chat Completions 兼容集
// ============================================================

import type { Api, Model } from './types';

export const MODELS = {
  anthropic: {
    'claude-3-5-haiku-20241022': {
      id: 'claude-3-5-haiku-20241022',
      name: 'Claude Haiku 3.5',
      api: 'anthropic-messages',
      provider: 'anthropic',
      baseUrl: 'https://api.anthropic.com',
      reasoning: false,
      input: ['text', 'image'],
      cost: {
        input: 0.8,
        output: 4,
        cacheRead: 0.08,
        cacheWrite: 1,
      },
      contextWindow: 200000,
      maxTokens: 8192,
    } satisfies Model<'anthropic-messages'>,
    'claude-3-5-haiku-latest': {
      id: 'claude-3-5-haiku-latest',
      name: 'Claude Haiku 3.5 (latest)',
      api: 'anthropic-messages',
      provider: 'anthropic',
      baseUrl: 'https://api.anthropic.com',
      reasoning: false,
      input: ['text', 'image'],
      cost: {
        input: 0.8,
        output: 4,
        cacheRead: 0.08,
        cacheWrite: 1,
      },
      contextWindow: 200000,
      maxTokens: 8192,
    } satisfies Model<'anthropic-messages'>,
    'claude-3-5-sonnet-20240620': {
      id: 'claude-3-5-sonnet-20240620',
      name: 'Claude Sonnet 3.5',
      api: 'anthropic-messages',
      provider: 'anthropic',
      baseUrl: 'https://api.anthropic.com',
      reasoning: false,
      input: ['text', 'image'],
      cost: {
        input: 3,
        output: 15,
        cacheRead: 0.3,
        cacheWrite: 3.75,
      },
      contextWindow: 200000,
      maxTokens: 8192,
    } satisfies Model<'anthropic-messages'>,
    'claude-3-5-sonnet-20241022': {
      id: 'claude-3-5-sonnet-20241022',
      name: 'Claude Sonnet 3.5 v2',
      api: 'anthropic-messages',
      provider: 'anthropic',
      baseUrl: 'https://api.anthropic.com',
      reasoning: false,
      input: ['text', 'image'],
      cost: {
        input: 3,
        output: 15,
        cacheRead: 0.3,
        cacheWrite: 3.75,
      },
      contextWindow: 200000,
      maxTokens: 8192,
    } satisfies Model<'anthropic-messages'>,
    'claude-3-7-sonnet-20250219': {
      id: 'claude-3-7-sonnet-20250219',
      name: 'Claude Sonnet 3.7',
      api: 'anthropic-messages',
      provider: 'anthropic',
      baseUrl: 'https://api.anthropic.com',
      reasoning: true,
      input: ['text', 'image'],
      cost: {
        input: 3,
        output: 15,
        cacheRead: 0.3,
        cacheWrite: 3.75,
      },
      contextWindow: 200000,
      maxTokens: 64000,
    } satisfies Model<'anthropic-messages'>,
    'claude-3-haiku-20240307': {
      id: 'claude-3-haiku-20240307',
      name: 'Claude Haiku 3',
      api: 'anthropic-messages',
      provider: 'anthropic',
      baseUrl: 'https://api.anthropic.com',
      reasoning: false,
      input: ['text', 'image'],
      cost: {
        input: 0.25,
        output: 1.25,
        cacheRead: 0.03,
        cacheWrite: 0.3,
      },
      contextWindow: 200000,
      maxTokens: 4096,
    } satisfies Model<'anthropic-messages'>,
    'claude-3-opus-20240229': {
      id: 'claude-3-opus-20240229',
      name: 'Claude Opus 3',
      api: 'anthropic-messages',
      provider: 'anthropic',
      baseUrl: 'https://api.anthropic.com',
      reasoning: false,
      input: ['text', 'image'],
      cost: {
        input: 15,
        output: 75,
        cacheRead: 1.5,
        cacheWrite: 18.75,
      },
      contextWindow: 200000,
      maxTokens: 4096,
    } satisfies Model<'anthropic-messages'>,
    'claude-3-sonnet-20240229': {
      id: 'claude-3-sonnet-20240229',
      name: 'Claude Sonnet 3',
      api: 'anthropic-messages',
      provider: 'anthropic',
      baseUrl: 'https://api.anthropic.com',
      reasoning: false,
      input: ['text', 'image'],
      cost: {
        input: 3,
        output: 15,
        cacheRead: 0.3,
        cacheWrite: 0.3,
      },
      contextWindow: 200000,
      maxTokens: 4096,
    } satisfies Model<'anthropic-messages'>,
    'claude-haiku-4-5': {
      id: 'claude-haiku-4-5',
      name: 'Claude Haiku 4.5 (latest)',
      api: 'anthropic-messages',
      provider: 'anthropic',
      baseUrl: 'https://api.anthropic.com',
      reasoning: true,
      input: ['text', 'image'],
      cost: {
        input: 1,
        output: 5,
        cacheRead: 0.1,
        cacheWrite: 1.25,
      },
      contextWindow: 200000,
      maxTokens: 64000,
    } satisfies Model<'anthropic-messages'>,
    'claude-haiku-4-5-20251001': {
      id: 'claude-haiku-4-5-20251001',
      name: 'Claude Haiku 4.5',
      api: 'anthropic-messages',
      provider: 'anthropic',
      baseUrl: 'https://api.anthropic.com',
      reasoning: true,
      input: ['text', 'image'],
      cost: {
        input: 1,
        output: 5,
        cacheRead: 0.1,
        cacheWrite: 1.25,
      },
      contextWindow: 200000,
      maxTokens: 64000,
    } satisfies Model<'anthropic-messages'>,
    'claude-opus-4-0': {
      id: 'claude-opus-4-0',
      name: 'Claude Opus 4 (latest)',
      api: 'anthropic-messages',
      provider: 'anthropic',
      baseUrl: 'https://api.anthropic.com',
      reasoning: true,
      input: ['text', 'image'],
      cost: {
        input: 15,
        output: 75,
        cacheRead: 1.5,
        cacheWrite: 18.75,
      },
      contextWindow: 200000,
      maxTokens: 32000,
    } satisfies Model<'anthropic-messages'>,
    'claude-opus-4-1': {
      id: 'claude-opus-4-1',
      name: 'Claude Opus 4.1 (latest)',
      api: 'anthropic-messages',
      provider: 'anthropic',
      baseUrl: 'https://api.anthropic.com',
      reasoning: true,
      input: ['text', 'image'],
      cost: {
        input: 15,
        output: 75,
        cacheRead: 1.5,
        cacheWrite: 18.75,
      },
      contextWindow: 200000,
      maxTokens: 32000,
    } satisfies Model<'anthropic-messages'>,
    'claude-opus-4-1-20250805': {
      id: 'claude-opus-4-1-20250805',
      name: 'Claude Opus 4.1',
      api: 'anthropic-messages',
      provider: 'anthropic',
      baseUrl: 'https://api.anthropic.com',
      reasoning: true,
      input: ['text', 'image'],
      cost: {
        input: 15,
        output: 75,
        cacheRead: 1.5,
        cacheWrite: 18.75,
      },
      contextWindow: 200000,
      maxTokens: 32000,
    } satisfies Model<'anthropic-messages'>,
    'claude-opus-4-20250514': {
      id: 'claude-opus-4-20250514',
      name: 'Claude Opus 4',
      api: 'anthropic-messages',
      provider: 'anthropic',
      baseUrl: 'https://api.anthropic.com',
      reasoning: true,
      input: ['text', 'image'],
      cost: {
        input: 15,
        output: 75,
        cacheRead: 1.5,
        cacheWrite: 18.75,
      },
      contextWindow: 200000,
      maxTokens: 32000,
    } satisfies Model<'anthropic-messages'>,
    'claude-opus-4-5': {
      id: 'claude-opus-4-5',
      name: 'Claude Opus 4.5 (latest)',
      api: 'anthropic-messages',
      provider: 'anthropic',
      baseUrl: 'https://api.anthropic.com',
      reasoning: true,
      input: ['text', 'image'],
      cost: {
        input: 5,
        output: 25,
        cacheRead: 0.5,
        cacheWrite: 6.25,
      },
      contextWindow: 200000,
      maxTokens: 64000,
    } satisfies Model<'anthropic-messages'>,
    'claude-opus-4-5-20251101': {
      id: 'claude-opus-4-5-20251101',
      name: 'Claude Opus 4.5',
      api: 'anthropic-messages',
      provider: 'anthropic',
      baseUrl: 'https://api.anthropic.com',
      reasoning: true,
      input: ['text', 'image'],
      cost: {
        input: 5,
        output: 25,
        cacheRead: 0.5,
        cacheWrite: 6.25,
      },
      contextWindow: 200000,
      maxTokens: 64000,
    } satisfies Model<'anthropic-messages'>,
    'claude-opus-4-6': {
      id: 'claude-opus-4-6',
      name: 'Claude Opus 4.6',
      api: 'anthropic-messages',
      provider: 'anthropic',
      baseUrl: 'https://api.anthropic.com',
      compat: { forceAdaptiveThinking: true },
      reasoning: true,
      thinkingLevelMap: { xhigh: 'max' },
      input: ['text', 'image'],
      cost: {
        input: 5,
        output: 25,
        cacheRead: 0.5,
        cacheWrite: 6.25,
      },
      contextWindow: 1000000,
      maxTokens: 128000,
    } satisfies Model<'anthropic-messages'>,
    'claude-opus-4-7': {
      id: 'claude-opus-4-7',
      name: 'Claude Opus 4.7',
      api: 'anthropic-messages',
      provider: 'anthropic',
      baseUrl: 'https://api.anthropic.com',
      compat: { forceAdaptiveThinking: true },
      reasoning: true,
      thinkingLevelMap: { xhigh: 'xhigh' },
      input: ['text', 'image'],
      cost: {
        input: 5,
        output: 25,
        cacheRead: 0.5,
        cacheWrite: 6.25,
      },
      contextWindow: 1000000,
      maxTokens: 128000,
    } satisfies Model<'anthropic-messages'>,
    'claude-sonnet-4-0': {
      id: 'claude-sonnet-4-0',
      name: 'Claude Sonnet 4 (latest)',
      api: 'anthropic-messages',
      provider: 'anthropic',
      baseUrl: 'https://api.anthropic.com',
      reasoning: true,
      input: ['text', 'image'],
      cost: {
        input: 3,
        output: 15,
        cacheRead: 0.3,
        cacheWrite: 3.75,
      },
      contextWindow: 200000,
      maxTokens: 64000,
    } satisfies Model<'anthropic-messages'>,
    'claude-sonnet-4-20250514': {
      id: 'claude-sonnet-4-20250514',
      name: 'Claude Sonnet 4',
      api: 'anthropic-messages',
      provider: 'anthropic',
      baseUrl: 'https://api.anthropic.com',
      reasoning: true,
      input: ['text', 'image'],
      cost: {
        input: 3,
        output: 15,
        cacheRead: 0.3,
        cacheWrite: 3.75,
      },
      contextWindow: 200000,
      maxTokens: 64000,
    } satisfies Model<'anthropic-messages'>,
    'claude-sonnet-4-5': {
      id: 'claude-sonnet-4-5',
      name: 'Claude Sonnet 4.5 (latest)',
      api: 'anthropic-messages',
      provider: 'anthropic',
      baseUrl: 'https://api.anthropic.com',
      reasoning: true,
      input: ['text', 'image'],
      cost: {
        input: 3,
        output: 15,
        cacheRead: 0.3,
        cacheWrite: 3.75,
      },
      contextWindow: 200000,
      maxTokens: 64000,
    } satisfies Model<'anthropic-messages'>,
    'claude-sonnet-4-5-20250929': {
      id: 'claude-sonnet-4-5-20250929',
      name: 'Claude Sonnet 4.5',
      api: 'anthropic-messages',
      provider: 'anthropic',
      baseUrl: 'https://api.anthropic.com',
      reasoning: true,
      input: ['text', 'image'],
      cost: {
        input: 3,
        output: 15,
        cacheRead: 0.3,
        cacheWrite: 3.75,
      },
      contextWindow: 200000,
      maxTokens: 64000,
    } satisfies Model<'anthropic-messages'>,
    'claude-sonnet-4-6': {
      id: 'claude-sonnet-4-6',
      name: 'Claude Sonnet 4.6',
      api: 'anthropic-messages',
      provider: 'anthropic',
      baseUrl: 'https://api.anthropic.com',
      compat: { forceAdaptiveThinking: true },
      reasoning: true,
      input: ['text', 'image'],
      cost: {
        input: 3,
        output: 15,
        cacheRead: 0.3,
        cacheWrite: 3.75,
      },
      contextWindow: 1000000,
      maxTokens: 64000,
    } satisfies Model<'anthropic-messages'>,
  },
  openai: {
    'gpt-4o': {
      id: 'gpt-4o',
      name: 'GPT-4o',
      api: 'openai-completions',
      provider: 'openai',
      baseUrl: 'https://api.openai.com/v1',
      reasoning: false,
      input: ['text', 'image'],
      cost: { input: 2.5, output: 10, cacheRead: 1.25, cacheWrite: 0 },
      contextWindow: 128000,
      maxTokens: 16384,
    },
    'gpt-4o-mini': {
      id: 'gpt-4o-mini',
      name: 'GPT-4o Mini',
      api: 'openai-completions',
      provider: 'openai',
      baseUrl: 'https://api.openai.com/v1',
      reasoning: false,
      input: ['text', 'image'],
      cost: { input: 0.15, output: 0.6, cacheRead: 0.075, cacheWrite: 0 },
      contextWindow: 128000,
      maxTokens: 16384,
    },
    o3: {
      id: 'o3',
      name: 'o3',
      api: 'openai-completions',
      provider: 'openai',
      baseUrl: 'https://api.openai.com/v1',
      reasoning: true,
      thinkingLevelMap: { off: null, minimal: 'low', low: 'low', medium: 'medium', high: 'high' },
      input: ['text', 'image'],
      cost: { input: 2, output: 8, cacheRead: 0.5, cacheWrite: 0 },
      contextWindow: 200000,
      maxTokens: 100000,
      compat: { supportsDeveloperRole: true, supportsReasoningEffort: true },
    },
    'o4-mini': {
      id: 'o4-mini',
      name: 'o4-mini',
      api: 'openai-completions',
      provider: 'openai',
      baseUrl: 'https://api.openai.com/v1',
      reasoning: true,
      thinkingLevelMap: { off: null, minimal: 'low', low: 'low', medium: 'medium', high: 'high' },
      input: ['text', 'image'],
      cost: { input: 1.1, output: 4.4, cacheRead: 0.275, cacheWrite: 0 },
      contextWindow: 200000,
      maxTokens: 100000,
      compat: { supportsDeveloperRole: true, supportsReasoningEffort: true },
    },
    'gpt-5': {
      id: 'gpt-5',
      name: 'GPT-5',
      api: 'openai-responses',
      provider: 'openai',
      baseUrl: 'https://api.openai.com/v1',
      reasoning: true,
      thinkingLevelMap: { off: null },
      input: ['text', 'image'],
      cost: { input: 1.25, output: 10, cacheRead: 0.125, cacheWrite: 0 },
      contextWindow: 400000,
      maxTokens: 128000,
    } satisfies Model<'openai-responses'>,
    'gpt-5-chat-latest': {
      id: 'gpt-5-chat-latest',
      name: 'GPT-5 Chat Latest',
      api: 'openai-responses',
      provider: 'openai',
      baseUrl: 'https://api.openai.com/v1',
      reasoning: false,
      input: ['text', 'image'],
      cost: { input: 1.25, output: 10, cacheRead: 0.125, cacheWrite: 0 },
      contextWindow: 128000,
      maxTokens: 16384,
    } satisfies Model<'openai-responses'>,
    'gpt-5-codex': {
      id: 'gpt-5-codex',
      name: 'GPT-5 Codex',
      api: 'openai-responses',
      provider: 'openai',
      baseUrl: 'https://api.openai.com/v1',
      reasoning: true,
      thinkingLevelMap: { off: null },
      input: ['text', 'image'],
      cost: { input: 1.25, output: 10, cacheRead: 0.125, cacheWrite: 0 },
      contextWindow: 400000,
      maxTokens: 128000,
    } satisfies Model<'openai-responses'>,
    'gpt-5-mini': {
      id: 'gpt-5-mini',
      name: 'GPT-5 Mini',
      api: 'openai-responses',
      provider: 'openai',
      baseUrl: 'https://api.openai.com/v1',
      reasoning: true,
      thinkingLevelMap: { off: null },
      input: ['text', 'image'],
      cost: { input: 0.25, output: 2, cacheRead: 0.025, cacheWrite: 0 },
      contextWindow: 400000,
      maxTokens: 128000,
    } satisfies Model<'openai-responses'>,
    'gpt-5-nano': {
      id: 'gpt-5-nano',
      name: 'GPT-5 Nano',
      api: 'openai-responses',
      provider: 'openai',
      baseUrl: 'https://api.openai.com/v1',
      reasoning: true,
      thinkingLevelMap: { off: null },
      input: ['text', 'image'],
      cost: { input: 0.05, output: 0.4, cacheRead: 0.005, cacheWrite: 0 },
      contextWindow: 400000,
      maxTokens: 128000,
    } satisfies Model<'openai-responses'>,
  },
} satisfies Record<string, Record<string, Model<Api>>>;
