// ============================================================
// Shared 统一出口：Extension 与 Webview 可序列化契约
// ============================================================

export { SCOUT_MODEL_PROVIDERS, THINKING_LEVELS, THINKING_STRENGTH_LEVELS } from './models.ts';
export type {
  ScoutConfiguredModelOverrideSettings,
  ScoutConfiguredModelSettings,
  ScoutCustomModelSettings,
  ScoutCustomModelsProviderConfig,
  ScoutCustomModelsProviderMetadata,
  ScoutCustomModelsProviderSettings,
  ScoutCustomModelsSaveSettings,
  ScoutCustomModelsSettings,
  ScoutModelApi,
  ScoutModelInfo,
  ScoutModelProvider,
  ThinkingLevel,
  ThinkingStrengthLevel,
} from './models.ts';

export {
  SCOUT_QUEUE_MODES,
  SCOUT_RUNTIME_SETTINGS_PATHS,
  SCOUT_SETTINGS_SCOPES,
  SCOUT_TRANSPORTS,
} from './settings.ts';
export type {
  ScoutBranchSummarySettings,
  ScoutCompactionSettings,
  ScoutPackageSource,
  ScoutQueueMode,
  ScoutRetryProviderSettings,
  ScoutRetrySettings,
  ScoutRuntimeSettings,
  ScoutRuntimeSettingsPatch,
  ScoutRuntimeSettingsPatchOperation,
  ScoutRuntimeSettingsPath,
  ScoutRuntimeSettingsState,
  ScoutSettingsScope,
  ScoutTransport,
} from './settings.ts';

export {
  EXTENSION_TO_WEBVIEW_MESSAGE_TYPES,
  SCOUT_PROTOCOL,
  WEBVIEW_TO_EXTENSION_MESSAGE_TYPES,
} from './protocol.ts';
export type {
  ExtensionEventMessage,
  ExtensionMessage,
  ScoutAgentEvent,
  ScoutAssistantMessage,
  ScoutAutoRetryEndEvent,
  ScoutAutoRetryStartEvent,
  ScoutBootstrapResult,
  ScoutBranchSummaryMessage,
  ScoutBusyKind,
  ScoutBusyState,
  ScoutCommandInfo,
  ScoutChangesReviewFile,
  ScoutChangesReviewHostMessage,
  ScoutChangesReviewModel,
  ScoutChangesReviewRow,
  ScoutChangesReviewSummary,
  ScoutChangesReviewSummaryFile,
  ScoutChangesReviewToken,
  ScoutChangesReviewTokenDiff,
  ScoutChangesReviewUpdateEvent,
  ScoutChangesReviewViewMode,
  ScoutChangesReviewWebviewMessage,
  ScoutCommandResult,
  ScoutCommandSource,
  ScoutCommandsResult,
  ScoutCompactionEndEvent,
  ScoutCompactionReason,
  ScoutCompactionResult,
  ScoutCompactionStartEvent,
  ScoutCompactionSummaryMessage,
  ScoutConfig,
  ScoutConfigResult,
  ScoutContent,
  ScoutContextUsage,
  ScoutContextUsageResult,
  ScoutControlMessage,
  ScoutCustomMessage,
  ScoutCustomModelsResult,
  ScoutDiagnostic,
  ScoutDiagnosticType,
  ScoutDomainEventType,
  ScoutExtensionListItem,
  ScoutExtensionTemplateInfo,
  ScoutExtensionTemplateId,
  ScoutExtensionsResult,
  ScoutExtensionsSettings,
  ScoutExtensionResourceScope,
  ScoutExtensionScope,
  ScoutFileChangeDiffPreview,
  ScoutFileChangeDetails,
  ScoutFileChangeReviewRef,
  ScoutFileEditPreview,
  ScoutFileMentionItem,
  ScoutFileMentionKind,
  ScoutFileMentionsResult,
  ScoutForkCandidate,
  ScoutForkCandidatesResult,
  ScoutForkResult,
  ScoutGenericCommandResult,
  ScoutGenericCommandResultType,
  ScoutImageContent,
  ScoutMessage,
  ScoutExtensionUIRequest,
  ScoutExtensionUIRequestClosedEvent,
  ScoutExtensionUIRequestClosedReason,
  ScoutNotificationMessage,
  ScoutProtocolCancel,
  ScoutProtocolError,
  ScoutProtocolKind,
  ScoutProtocolPayloadType,
  ScoutProtocolRequest,
  ScoutProtocolResponse,
  ScoutProtocolResponsePayload,
  ScoutProtocolResponsePayloadType,
  ScoutProtocolRoute,
  ScoutProtocolService,
  ScoutQueuedFollowUp,
  ScoutQueuedMessage,
  ScoutQueuedMessageDelivery,
  ScoutQueueState,
  ScoutRuntimeEvent,
  ScoutRuntimeExtensionEvent,
  ScoutRuntimeSettingsResult,
  ScoutRuntimeStateUpdateEvent,
  ScoutSaveCustomModelsResult,
  ScoutSaveRuntimeSettingsResult,
  ScoutSessionListItem,
  ScoutSessionStats,
  ScoutSessionTreeNode,
  ScoutSessionTreeNodeKind,
  ScoutSessionTreeToolArgument,
  ScoutSessionTreeToolCall,
  ScoutSessionsResult,
  ScoutStateResult,
  ScoutTaskHistoryPurpose,
  ScoutTaskHistoryResult,
  ScoutTaskItem,
  ScoutTextContent,
  ScoutThinkingContent,
  ScoutToolCallContent,
  ScoutToolCallPreview,
  ScoutToolCallPreviewUpdateEvent,
  ScoutToolExecutionResult,
  ScoutToolResultMessage,
  ScoutTreeResult,
  ScoutUserMessage,
  ScoutWebviewState,
  ScoutWebviewSurface,
  SourceInfo,
  SourceOrigin,
  SourceScope,
  ToolInfo,
  ToolPresentationMetadata,
  WebviewMessage,
  WebviewRequestPayload,
} from './protocol.ts';
